### PR TITLE
Add dependabot config

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Checks weekly and updates @honeycombio/integrations-team.

### CODE REVIEW

**Review by martin308 — COMMENTED** [review]
This is probably worth having to be consistent with the other repos. I'm not sure how much value we will get out of it though as we use the gemfiles in the gemfiles directory and we purposely don't check in lock files for those. 

Maybe we should set the directory property to gemfiles and see what happens?

**Comment by MikeGoldsmith** [comment]
Yeah, sure - lets give that a try 👍

**Comment by robbkidd** [comment]
Rebased branch to latest `main`.

**Review by robbkidd — APPROVED** [review]
Let's give it a whirl!

a cyberman dancing

**Pull request merged**
