### PR TITLE
Prepare v2.2.1 release

### PR DESCRIPTION
**Pull request by MikeGoldsmith**

### CODE REVIEW

**Comment by martin308** [comment]
I don't see any changes to release since the last release in the commit history?

**Comment by MikeGoldsmith** [comment]
The only change is adding the `.editorconfig` file. It's a minimal change, but we're trying to get into the habit of releasing regularly and ensuring everyone knows the release process for each repo.

**Comment by MikeGoldsmith** [comment]
Oh, and there is some extra docs to describe how to run tests.

**Comment by martin308** [comment]
Neither of which will impact anyone using the gem though right? I feel like a release should contain some actual code changes that will impact users of the gem

**Comment by MikeGoldsmith** [comment]
Closing as this proposed release does not include any SDK user facing changes.

**Pull request closed without merging**
