### PR TITLE
Use nil for config dataset when empty

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
An empty dataset can cause issues and should default to `nil`.

### CODE REVIEW

**Review by irvingpop — APPROVED** [review]
Thanks for the quick turnaround Mike!!

**Comment by paulosman** [comment]
LGTM - but do we know why a number of tests are now failing?

**Comment by irvingpop** [comment]
Ah yeah looks like all the aws3 tests are failing

**Review by martin308 — CHANGES_REQUESTED** [review]
We probably need to add a lot more tests for dataset being nil in various places, I think most of the tests provide an actual dataset right now

**Comment by martin308** [comment]
@paulosman looks like a breaking change in a minor version bump of the aws dynamo gem

**Comment by MikeGoldsmith** [comment]
Thanks for fixing the AWS dynamo tests in #119.

I can add more testing around having a nil dataset. @martin308 can you give any advice on where to focus?

**Comment by paulosman** [comment]
When building a URI with a `nil` dataset, I think libhoney will still interpolate it as an empty string.

**Comment by MikeGoldsmith** [comment]
Closing in favour of https://github.com/honeycombio/libhoney-rb/pull/67

**Pull request closed without merging**
