### PR TITLE
maint: drop support for Ruby < 2.5 and Rails < 5.0

### LINKED ISSUE #224: Failing nightly build - Rails is unhappy
**Versions**

- Ruby: 2.2, 2.3, 2.4
- Beeline: [main](https://github.com/honeycombio/beeline-ruby/tree/b679afbfaa957121d685456b2d8777361b6ac2e1) as of b679afbfaa957121d685456b2d8777361b6ac2e1

**Steps to reproduce**

1. See Rails failures in [sad nightly build](https://app.circleci.com/pipelines/github/honeycombio/beeline-ruby/1824/workflows/76aa2461-441a-4c26-a601-9014a83c7cc2)

**Additional context**

### PR DESCRIPTION
**Pull request by robbkidd**
## Which problem is this PR solving?

- Fixes #224
- Closes #226 - supersedes these changes opt for simplifying Beeline support in its maintenance/sunsetting days

Old, unmaintained versions of things are starting to make the CI matrix of old combinations creak as the Ruby ecosystem starts to firmly drop support for those old, unmaintained versions.

* [Ruby 2.4 was end-of-life'd](https://endoflife.date/ruby) 3 years ago (Mar 2020).
* [Rails 4.2 was end-of-life'd](https://endoflife.date/rails) 6 years ago (Apr 2017)

## Short description of the changes

- Removes Ruby < 2.5 and Rails < 5.0 from the CI matrix
- Remove examples/rails41
- Change the beeline's required_ruby_version from ">= 2.2.0" to ">= 2.5.0"
- Appease Rubocop violations for new TargetRubyVersion of 2.5

### CODE REVIEW

**Review by MikeGoldsmith — APPROVED** [review]

**Review by JamieDanielson — APPROVED** [review]
it is time

**Comment by robbkidd** [comment]
```
Running RuboCop...
Inspecting 78 files
...C..........................................................................

Offenses:

honeycomb-beeline.gemspec:18:32: C: Gemspec/RequiredRubyVersion:
    required_ruby_version (2.5, declared in honeycomb-beeline.gemspec) and 
    TargetRubyVersion (2.2, which may be specified in .rubocop.yml) should be equal.
  spec.required_ruby_version = ">= 2.5.0"
                               ^^^^^^^^^^
```

OK … updating TargetRubyVersion in rubocop config to Ruby 2.5 …

```
❯ bundle exec rubocop --format offenses
 78/78 files

8   Layout/EmptyLinesAroundBlockBody
8   Layout/TrailingWhitespace
6   Layout/IndentationWidth
5   Style/RedundantFreeze
5   Style/SafeNavigation
4   Layout/RescueEnsureAlignment
4   Style/RedundantBegin
2   Layout/BlockAlignment
2   Performance/RegexpMatch
1   Style/UnpackFirst
--
45  Total
```

can open, worms everywhere

Workin' on it.

**Comment by MikeGoldsmith** [comment]
@robbkidd are you happy for this PR to be merged now?

**Comment by robbkidd** [comment]
> @robbkidd are you happy for this PR to be merged now?

Yes. Yes, I am.

**Pull request merged**
